# Generated by Django 5.2 on 2026-04-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='data_year',
            field=models.IntegerField(default=2025),
        ),
    ]
