# Generated by Django 5.2 on 2026-04-27 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_add_data_year_to_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('intro', 'Intro'), ('pricing', 'Pricing'), ('followup', 'Follow-Up')], max_length=20)),
                ('subject_line', models.CharField(blank=True, max_length=255)),
                ('email_content', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='stage_docs/')),
                ('trigger_days', models.IntegerField(default=4)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_configs', to='campaigns.product')),
            ],
            options={
                'db_table': 'product_stage_configs',
                'ordering': ['stage'],
                'unique_together': {('product', 'stage')},
            },
        ),
    ]
