# Generated by Django 5.2 on 2026-04-27 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_country', models.CharField(max_length=10)),
                ('company_website', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(choices=[('discovered', 'Discovered'), ('intro_sent', 'Intro Sent'), ('pricing_sent', 'Pricing Sent'), ('pricing_followup', 'Pricing Followup'), ('meeting_set', 'Meeting Set'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='discovered', max_length=30)),
                ('auto_flow_paused', models.BooleanField(default=False)),
                ('volza_data', models.JSONField(default=dict)),
                ('pricing_trend', models.JSONField(default=dict)),
                ('purchase_history', models.JSONField(default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(choices=[('volza', 'Volza'), ('lusha', 'Lusha'), ('manual', 'Manual')], default='volza', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('lusha_raw', models.JSONField(default=dict)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='leads.lead')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('intro_email', 'Intro Email'), ('follow_up_call', 'Follow Up Call'), ('pricing_email', 'Pricing Email'), ('pricing_followup_email', 'Pricing Follow-Up Email'), ('meeting_scheduled', 'Meeting Scheduled'), ('note', 'Note'), ('ai_draft_generated', 'AI Draft Generated'), ('ai_draft_approved', 'AI Draft Approved'), ('ai_draft_rejected', 'AI Draft Rejected'), ('deal_closed', 'Deal Closed'), ('manual_takeover', 'Manual Takeover')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='leads.lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
