# Generated by Django 5.2 on 2026-04-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_update_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company_country',
            field=models.CharField(max_length=100),
        ),
    ]
