# Generated by Django 5.2 on 2026-04-27 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost')], max_length=10)),
                ('closed_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_deals', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='leads.lead')),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_event_id', models.CharField(blank=True, max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('meeting_link', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='leads.contact')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='leads.lead')),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
