# Generated by Django 5.2 on 2026-04-27 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=500)),
                ('thread_type', models.CharField(choices=[('intro', 'Intro'), ('pricing', 'Pricing'), ('followup', 'Follow-Up'), ('negotiation', 'Negotiation')], max_length=20)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=200)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='leads.contact')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='leads.lead')),
            ],
            options={
                'db_table': 'email_threads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField()),
                ('gmail_message_id', models.CharField(blank=True, max_length=200)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.emailthread')),
            ],
            options={
                'db_table': 'email_messages',
                'ordering': ['sent_at'],
            },
        ),
    ]
